### PR TITLE
Set iOS deployment target to 8.0

### PR DESCRIPTION
**Pull request by gfontenot**
This was set back to 7.0 in 055c87b, but Framework targets aren't actually
supported below iOS 8.0. We can leave the target in the podspec, but there's
no point in setting the deployment target on iOS lower than we can actually
support.

### CODE REVIEW

**Comment by jeffh** [comment]
Although Xcode creates warnings about iOS frameworks not running on older runtimes, it actually still works (at least in the simulator). While I'm not sure if it works on physical devices, it does allow people to use Fox in projects that have a older deployment target.

I just went back and verified that Fox works on iOS 7.1 simulator in Xcode 6.3 beta. Let me know if there was some other concerns that you might of had.

**Comment by gfontenot** [comment]
Wild. My main concern were the warnings. I only noticed it because I was trying to fix the build error in #39, so if it doesn't bother you, I'm OK with throwing this PR away.

**Comment by jeffh** [comment]
Ok, I'm closing it, thanks again @gfontenot.

**Comment by gfontenot** [comment]
fwiw, Carthage/Carthage#351 and AlamoFire/AlamoFire#352 are probably related to this. Not sure if it really matters since you almost certainly aren't shipping apps to the store with Fox included, but something to be aware of.

**Comment by jeffh** [comment]
Thanks, I'll keep that it mind!

**Pull request closed without merging**
